#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")"

if ! command -v rm &> /dev/null; then
  echo -e "\e[31mE: rm Is Not Installed.\e[0m" >&2
  exit 1
fi

if ! command -v chmod &> /dev/null; then
  echo -e "\e[31mE: chmod Is Not Installed.\e[0m" >&2
  exit 1
fi

if [ "$(whoami)" != "root" ]; then
    echo -e "\e[31mE: You have to run as Superuser\e[0m" >&2
    exit 1
fi

if ! command -v ./lib/$1/Reinstall.sh &> /dev/null; then
    echo -e "\e[31mE: Unable To Locate Package $1\e[0m" >&2
    exit 1
else
    chmod +x ./lib/$1/Reinstall.sh &> /dev/null
    ./lib/$1/Reinstall.sh
    exit 1
fi
